# Generated by Django 2.1.5 on 2019-02-08 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=15)),
                ('ativado', models.BooleanField()),
                ('segunda', models.BooleanField()),
                ('terca', models.BooleanField()),
                ('quarta', models.BooleanField()),
                ('quinta', models.BooleanField()),
                ('sexta', models.BooleanField()),
                ('sabado', models.BooleanField()),
                ('domingo', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
    ]
