# Generated by Django 2.1.5 on 2019-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190216_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ativado',
            field=models.BooleanField(default=False),
        ),
    ]
